org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.debug=false
minecraft_version=1.21.0
minecraft_version_range=[1.21.0,1.22)
neo_version=21.0.167
neo_version_range=[21,)
loader_version_range=[4,)
mapping_channel=parchment
mapping_version=2024.06.02
mod_id=realism
mod_name=Realism
mod_license=All-Rights-Reserved
mod_version=0.0.1
mod_group_id=net.liopyu
mod_authors=Liopyu
mod_description=
